config/routes.rb
Dealsformommy::Application.routes.draw do

  get "errors/fourofour"

  get "errors/fivehundred"

    ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  mount Resque::Server, :at => "/resque"  

  root :to => "members#new"

  resources :members
  resources :sessions, :only => [:new, :create, :destroy]
  resources :advertisers, :only => [:new, :create]
	resources :offers, :only => [:index]
  resources :coregs do
    resources :coreg_optins
  end

  match '/signin(/:token)', :to => 'sessions#new', :as => 'signin'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contest' => 'contest#index'
  match '/contest/free-diapers-for-year' => 'contest#free_diapers_for_year'

  match '/free-diapers' => redirect('/saving-form1?f=full_form_member&utm_source=magazine&utm_medium=healthym=b&utm_campaign=free-diapers')

  match '/articles' => 'articles#index'
  match 'articles/top-reasons-for-coupon-use-by-women' =>'articles#top_reasons_for_coupon_use_by_women'
  match '/deals-for-mommy-coupons-savings-and-samples' => 'articles#deals_for_mommy_coupons_savings_and_samples', :as => 'deals_for_mommy_coupons_savings_and_samples'
  match '/baby-coupons-gerber-and-other-infant-formula' =>'articles#baby_coupons_gerber_and_other_infant_formula', :as => 'baby_coupons_gerber_and_other_infant_formula'
  match '/diaper-coupons-making-moms-lives-easier' => 'articles#diaper_coupons_making_moms_lives_easier', :as => 'diaper_coupons_making_moms_lives_easier'
  match '/is-enfamil-the-best-for-your-baby' => 'articles#is_enfamil_the_best_for_your_baby', :as => 'is_enfamil_the_best_for_your_baby'
  match '/money-saving-tips-for-moms-baby-coupons-online' =>'articles#money_saving_tips_for_moms_baby_coupons_online', :as => 'money_saving_tips_for_moms_baby_coupons_online'
  match '/about' => 'pages#about', :as => 'about'
	match '/success' => 'pages#success'
	match '/fail' => 'pages#fail'
  match '/privacy-policy' => 'pages#privacy'
  match '/sitemap' => 'pages#sitemap'
  match '/terms-of-use' => 'pages#terms'
  match '/how-it-works' => 'pages#howitworks', :as => 'howitworks'
	match '/get-your-dashboard' => 'members#get_your_dashboard'
  match '/coupons' => 'pages#coupons', :as => 'coupons'
  match '/freebies-and-discounts' => 'pages#freebies', :as => 'freebies'
  match '/travel-deals' => 'pages#traveldeals', :as => 'traveldeals'
  match '/hot-deals' => 'pages#hotdeals', :as => 'hotdeals'
  match '/dbunsub' => 'dbunsub#new', :as => 'dbunsub'
  match '/unsubscribe' => 'members#unsubscribe', :as => 'unsubscribe'
  
  match '/advertisers', :to => 'advertisers#new', :as =>'advertisers'
  match '/flow_step' => 'members#flow_step'
  match '/step2' => 'members#step_two'
  match '/step3' => 'members#step_three'
  match '/promo/:promo' => 'members#promo'
  match '/home' => 'members#home', :as => 'home'
	match '/offers' => 'offers#index', :as => 'offers'
  match '/signup' => redirect('/')
  match '/profile', :to => 'members#edit'
  match '/reset_password', :to => 'members#reset_password', :as => 'reset_password'
  match '/recover_password', :to => 'members#recover_password', :as => 'recover_password'
	match '/newsletter' => 'pages#newsletter'
  match '/advertisers' => 'advertisers#new', :as => 'feature_a_deal'
  match '/kiwi' => redirect('/?utm_source=KiwiMag&utm_medium=DMInsert&utm_campaign=052012')
  match '/kiwimag' => redirect('/?utm_source=KiwiMag&utm_medium=DMInsert&utm_campaign=052012')
  match '/kiwimagazine' => redirect('/?utm_source=KiwiMag&utm_medium=DMInsert&utm_campaign=052012')
  match '/saving-form1', :controller => 'members', :action => 'new', :f => 'full_form_member'
  match '/saving-form1-virtualpiggy', :controller => 'members', :action => 'new', :f => 'full_form_member_virtualpiggy'
  match '/saving-form1-moolala', :controller => 'members', :action => 'new', :f => 'full_form_member_moolala'
  match '/saving-form1-shopsocial', :controller => 'members', :action => 'new', :f => 'full_form_member_shopsocial'
  match '/virtualpiggy', :controller => 'members', :action => 'new', :x => 'pm_virtual_piggy'

  match'/mom365' => redirect('/saving-form1?utm_source=magazine&utm_medium=mom365&utm_campaign=free-diapers')
  match '/:path', :controller => 'content_pages', :action => 'show'

  namespace 'api' do
    match '/v1/:action' => 'v1'
    scope "/optins" do
      post "/register" => "coreg_optins#register_optin"
      get  "coregs" => "coreg_optins#list"
      get  "coreg_optins/:id" => "coreg_optins#confirm"
   end
  end

   match '*a', :to => 'errors#fourofour'
end

app/models/advertiser.rb
class Advertiser
	include ActiveModel::Validations
	validates :email,
		:presence => {:message => '^Email is required'}
	validates :business_name,
		:presence => {:message => '^Business Name is required'}
	validates :first_name,
		:presence => {:message => '^First Name is required'}
	validates :last_name,
		:presence => {:message => '^Last Name is required'}
	validates :phone,
		:presence => {:message => '^Phone is required'}

	attr_accessor :id, :email, :business_name, :first_name, :last_name, :phone, :address, :city, :state, :postal, :phone, :website, :business_desc, :deal_desc
  def initialize(attributes={})
    attributes.each do |key, value|
			self.send("#{key}=", value)
		end
		@attributes = attributes
  end
	
	def read_attribute_for_validation(key)
    @attributes[key]
	end

  def to_key
  end

	def save
    if self.valid?
      MemberMailer.advertiser_email(self).deliver
      return true
    end
			return false
  end
end

app/controllers/advertisers_controller.rb
class AdvertisersController < ApplicationController

	TITLE = 'Advertise With Us'
	META_DESCRIPTION = 'Advertise with Deals For Mommy and get your Deal featured to our members.'
	META_KEYWORDS = 'deals for mommy, mommy deals, deals for moms, daily deals for moms, mom coupons, advertise, ads, promote, marketing, feature a deal, promote a deal'
	
	def new
		@title = TITLE
		@meta_description = META_DESCRIPTION
		@meta_keywords = META_KEYWORDS
	end

  def create
		@title = TITLE
		@meta_description = META_DESCRIPTION
		@meta_keywords = META_KEYWORDS
    @advertiser = Advertiser.new(params[:advertiser])
		if @advertiser.save
			redirect_to('/', :notice => 'Message has been successfully sent')
		else
			render :new
		end
  end

end

app/views/advertisers/new.html.erb
<div id="mainDiv" class="about">
	<h1 class="color2">Feature a Deal</h1>
	<br class="clear"/>
	<%= link_to image_tag("delias-message3.gif", :alt => "Advertise Deals and Coupons", :style=>"float:right;margin-left:15px"), :howitworks %>
	<p>Have a deal or special you'd like to feature to DealsForMommy members, tell us about it. Once we've had a chance to check out your company and deal, we'll get back with you regarding the next steps. Thanks... we're excited to get to know you better.</p>
	<%= simple_form_for(:advertiser, :url => advertisers_path, :html => {:method => :post, :novalidate => true, :class => ''} ) do |f| %>
	<fieldset><legend class="hidden"></legend>
		<%= f.error_messages :header_message => '' %>
		<div style="float:left;width:100%"><%= f.input :business_name, :label => 'Business Name' %></div>
		<div style="float:left;width:100%"><%= f.input :email, :label => 'Email' %></div>
		<div style="float:left;width:100%"><%= f.input :first_name, :label => 'First Name' %></div>
		<div style="float:left;width:100%"><%= f.input :last_name, :label => 'Last Name ' %></div>
		<div style="float:left;width:100%"><%= f.input :address, :label => 'Address', :required => false %></div>
		<div style="float:left;width:100%">
			<div style="width:200px;float:left;"><%= f.input :city, :label => 'City', :input_html => { :class => 'formFieldInputLarge'} ,:required => false  %></div>
			<div style="width:70px;float:left;"><%= f.input :state, :label => 'State', :collection => State.all.map { |state| state.code }, :required => false, :input_html =>{:style =>'clear: left'} %></div>
		<div  style="width:200px;float:left;"><%= f.input :postal, :label => 'Postal', :input_html => {:size => '10',:style =>'clear: left'}, :required => false %></div>
		</div>
		<br class="clear" />
		<div style="float:left;width:100%"><%= f.input :phone, :label => 'Phone'  %></div>
		<div style="float:left;width:100%"><%= f.input :website, :label => 'Website', :required => false  %></div>
		<div style="float:left;width:100%"><%= f.input :business_desc, :as => :text, :required => false , :input_html => { :style => 'width:324px;height:100px'}, :label => 'Tell us a little bit about your business' %></div>
		<div style="float:left;width:100%"><%= f.input :deal_desc, :as => :text, :required => false , :input_html => { :style => 'width:324px;height:100px'}, :label => 'Tell us a little bit about your deal offer' %></div>
		<div class="clear"></div><br />
		<div class="actions">
			<%= image_submit_tag 'bt-submit.gif', :name => 'submitButton',  :class => 'ml10', :style => 'width:119px;height:38px' %>
		</div>
	</fieldset>
<% end %>
</div>
	<br class="clear" />