config/routes.rb
Dealsformommy::Application.routes.draw do

  get "errors/fourofour"

  get "errors/fivehundred"

    ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  mount Resque::Server, :at => "/resque"  

  root :to => "members#new"

  resources :members
  resources :sessions, :only => [:new, :create, :destroy]
  resources :advertisers, :only => [:new, :create]
	resources :offers, :only => [:index]
  resources :coregs do
    resources :coreg_optins
  end

  match '/signin(/:token)', :to => 'sessions#new', :as => 'signin'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contest' => 'contest#index'
  match '/contest/free-diapers-for-year' => 'contest#free_diapers_for_year'

  match '/free-diapers' => redirect('/saving-form1?f=full_form_member&utm_source=magazine&utm_medium=healthym=b&utm_campaign=free-diapers')

  match '/articles' => 'articles#index'
  match 'articles/top-reasons-for-coupon-use-by-women' =>'articles#top_reasons_for_coupon_use_by_women'
  match '/deals-for-mommy-coupons-savings-and-samples' => 'articles#deals_for_mommy_coupons_savings_and_samples', :as => 'deals_for_mommy_coupons_savings_and_samples'
  match '/baby-coupons-gerber-and-other-infant-formula' =>'articles#baby_coupons_gerber_and_other_infant_formula', :as => 'baby_coupons_gerber_and_other_infant_formula'
  match '/diaper-coupons-making-moms-lives-easier' => 'articles#diaper_coupons_making_moms_lives_easier', :as => 'diaper_coupons_making_moms_lives_easier'
  match '/is-enfamil-the-best-for-your-baby' => 'articles#is_enfamil_the_best_for_your_baby', :as => 'is_enfamil_the_best_for_your_baby'
  match '/money-saving-tips-for-moms-baby-coupons-online' =>'articles#money_saving_tips_for_moms_baby_coupons_online', :as => 'money_saving_tips_for_moms_baby_coupons_online'
  match '/about' => 'pages#about', :as => 'about'
	match '/success' => 'pages#success'
	match '/fail' => 'pages#fail'
  match '/privacy-policy' => 'pages#privacy'
  match '/sitemap' => 'pages#sitemap'
  match '/terms-of-use' => 'pages#terms'
  match '/how-it-works' => 'pages#howitworks', :as => 'howitworks'
	match '/get-your-dashboard' => 'members#get_your_dashboard'
  match '/coupons' => 'pages#coupons', :as => 'coupons'
  match '/freebies-and-discounts' => 'pages#freebies', :as => 'freebies'
  match '/travel-deals' => 'pages#traveldeals', :as => 'traveldeals'
  match '/hot-deals' => 'pages#hotdeals', :as => 'hotdeals'
  match '/dbunsub' => 'dbunsub#new', :as => 'dbunsub'
  match '/unsubscribe' => 'members#unsubscribe', :as => 'unsubscribe'
  
  match '/advertisers', :to => 'advertisers#new', :as =>'advertisers'
  match '/flow_step' => 'members#flow_step'
  match '/step2' => 'members#step_two'
  match '/step3' => 'members#step_three'
  match '/promo/:promo' => 'members#promo'
  match '/home' => 'members#home', :as => 'home'
	match '/offers' => 'offers#index', :as => 'offers'
  match '/signup' => redirect('/')
  match '/profile', :to => 'members#edit'
  match '/reset_password', :to => 'members#reset_password', :as => 'reset_password'
  match '/recover_password', :to => 'members#recover_password', :as => 'recover_password'
	match '/newsletter' => 'pages#newsletter'
  match '/advertisers' => 'advertisers#new', :as => 'feature_a_deal'
  match '/kiwi' => redirect('/?utm_source=KiwiMag&utm_medium=DMInsert&utm_campaign=052012')
  match '/kiwimag' => redirect('/?utm_source=KiwiMag&utm_medium=DMInsert&utm_campaign=052012')
  match '/kiwimagazine' => redirect('/?utm_source=KiwiMag&utm_medium=DMInsert&utm_campaign=052012')
  match '/saving-form1', :controller => 'members', :action => 'new', :f => 'full_form_member'
  match '/saving-form1-virtualpiggy', :controller => 'members', :action => 'new', :f => 'full_form_member_virtualpiggy'
  match '/saving-form1-moolala', :controller => 'members', :action => 'new', :f => 'full_form_member_moolala'
  match '/saving-form1-shopsocial', :controller => 'members', :action => 'new', :f => 'full_form_member_shopsocial'
  match '/virtualpiggy', :controller => 'members', :action => 'new', :x => 'pm_virtual_piggy'

  match'/mom365' => redirect('/saving-form1?utm_source=magazine&utm_medium=mom365&utm_campaign=free-diapers')
  match '/:path', :controller => 'content_pages', :action => 'show'

  namespace 'api' do
    match '/v1/:action' => 'v1'
    scope "/optins" do
      post "/register" => "coreg_optins#register_optin"
      get  "coregs" => "coreg_optins#list"
      get  "coreg_optins/:id" => "coreg_optins#confirm"
   end
  end

   match '*a', :to => 'errors#fourofour'
end

app/views/partials/_cp_offer.html.erb
    <!-- Featured Deal Div -->
    <div id="featured-deal">
      <div id="featured-deal-header">
        <h4><%= link_to 'CanvasPeople.com', 'http://parentmediagroup.go2jump.org/aff_c?offer_id=9&aff_id=640&aff_sub=default_offer&url_id=86', :target=>'_blank' %></h4><!--[if lte ie 7]>
      <b></b><![endif]-->
      </div>
      <div class="featured-deal-body">
        <div class="fdb-top">
          <span>Redeem at Home</span><br/>
          <p>Free	8 x 10 Canvas Portrait or $50 towards a larger size.</p>
        </div>
        <br class="clear"/>
        <div>
          <div class="fdb-column-1"><%= image_tag '042111-dfm-mom2.jpg', :size => '213x129', :style => 'align:left' %></div>
          <div class="fdb-column-2">
            <ul class="featured-price-details">
								<li class="fpd-first">FREE</li>
              <li><span>Value:</span> <strong>$50</strong></li>
              <li><span>Discount:</span> <strong>100%</strong></li>
              <li><span>Savings:</span> <strong>$50</strong></li>
            </ul>
          </div>
          <div class="fdb-column-3">
            <ul>
              <li><%= link_to (image_tag 'see-deal-link.gif', :size => '85x28'), 'http://parentmediagroup.go2jump.org/aff_c?offer_id=9&aff_id=640&aff_sub=default_offer&url_id=86', :target=>'_blank' %></li>
              <li>&nbsp;</li>
              <li>&nbsp;</li>
              <li><span><br/></span><br/><%= image_tag 'http://www.canvaspeople.com/images/header-logo.jpg', :size => "74x34", :alt=>"" %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
        <!-- Start CoReg -->
      <div style="float:left;">
      <%= image_tag 'smartone-90x90__2_.jpg', :size=>'90x90', :style=>"float:right" %></li>
            <h5> Save on Weight Watchers® Smart Ones® products!</h5>
      <h3>Save $4.00 when you sign up for our emails! Get info on new products, recipes, coupons and more.</h3>
            </div>
    <!-- End coReg -->
    <!-- End of Featured Deal Div -->

app/views/partials/_daily_promo.html.erb
		<!-- Start dailyPromo -->
		<div id="dailyPromo">
			<div style="float:left;">
            <h5>Register today and receive this Instant Deal</h5>
			<h3>Today's Instant Deal: <%= Time.now.in_time_zone.strftime("%B %d, %Y") %></h3>
			<h2>Value: $50</h2>
            </div>
            <div class="ad"><p><strong>All Members Today Receive</strong><br /> a free 8 x 10 Canvas Portrait<br />or $50 towards a larger size<br /><span style="font-size:10px">(pay only s&h)</span></p></div>
		</div>
		<!-- End dailyPromo -->

app/views/partials/_delias_promise.html.erb
<%= image_tag 'thmb-Delia.gif',:alt => 'Delia helps you find Deals', :size => '44x45', :align => 'left', :style => "float:left;margin:0 10px 20px 0;text-align: left;"  %>
<script>utmx_section("section1")</script>
<h1>Delia's Promise</h1>
<p>The easiest way to save on the things you already buy, from the brands you know and trust. Every day, I will scour the internet to bring you the latest instant coupons, local deals and samples.</p>
</noscript>

app/views/partials/_division_dropdown.erb
<h3 class="blockHead">Deals of the Day near <span style="color:#f00"><%= @location_display %>&nbsp;&nbsp;
		<% if @groupon_divisions %>
			<% if controller.controller_name == 'members' %>
				<%= form_tag '/home', :style => "display:inline" do |f| %>
					<%= select_tag "divisions", options_from_collection_for_select(@groupon_divisions, "id", "name",@division_id),{:onchange => "this.form.submit();", :style => "float:none;font-size:11px;height:auto" } %>
				<% end %>
			<% else %>
				<%= form_tag '/offers', :style => "display:inline" do |f| %>
					<%= select_tag "divisions", options_from_collection_for_select(@groupon_divisions, "id", "name",@division_id),{:onchange => "this.form.submit();", :style => "float:none;font-size:11px;height:auto" } %>
				<% end %>
			<% end %>
		<% end %></span>
	<% if !@other_deals.nil? and @other_deals.length > 2 %>
		<div style="float:right;text-align:right;font-size:13px;margin:0 20px 0 0; *margin:-30px 20px 0 0"><%= link_to "See More Deals >>", offers_path %></div>
	<% end %>
</h3>

app/views/partials/_enfamil_promo.html.erb
<h2>Save on Enfamil Formula and so much more!</h2>
<p>Your baby is likely to need high quality formula for the foreseeable future... you might as well save on formula as much as you can. Members of deals for mommy have saved thousands on everything you need for your baby. From formula to diapers to clothes and more. Join in on the savings, the community would love to have you.</p>

app/views/partials/_flash.html.erb
<script language="javascript" type="text/javascript">
<% [:info, :notice, :error].each do |key| %>
  <% if flash[key] %>
    $.n.error("<%=flash[key]%>",{fadeSpeed:1500, effect:'slide', close:"close"})
  <% end %>
<% end %>
</script>

app/views/partials/_group_commerce_email_template.html.erb
<table cellspacing="0" cellpadding="0" style="border-collapse: collapse">
    <tr>
        <td width="700">
            <img src= "http://link.ixs1.net/site/8554/images/gc_email-new_02.jpg" width="700" height="22" border="0"  style="display:block;"/>
        </td>
    </tr>
    <tr>
        <td width="700">
            <!--Main Deal Table -->
            <table width="700" border="0" cellspacing="0" cellpadding="0">

                <tr>
                    <td width="44">
                        <img src= "http://link.ixs1.net/site/8554/images/gc_email-new_03.jpg" width="44" height="256" border="0"    style="display:block;"/>
                    </td>
                    <td width="340">
                        <a href="#"><img src="<%= @first_deal.offer.images.first.sizes[0].url %>" width="340" height="255" border="0"    style="display:block;"/></a>
                    </td>
                    <td width="20">
                        <img src= "http://link.ixs1.net/site/8554/images/gc_email-new_05.jpg" width="20" height="256" border="0"    style="display:block;"/>
                    </td>
                    <td width="257" valign="top" style="font-family:Arial, Helvetica, sans-serif; font-size:25px;">
                        <!--View Deal Table -->
                        <table width="257" border="0" cellspacing="0" cellpadding="0">

                            <tr>
                                <td width="257" style="color:#000000; font-family:Arial, Helvetica, sans-serif; font-size:18px;line-height:23px" valign="top">
                                    <strong><%= @first_deal.offer.headline %></strong>
                                    <img src= "http://link.ixs1.net/site/8554/images/gc_email-new_08.jpg" width="257" height="85" border="0"/>

                                    <!--Button Area Table -->

                                    <table width="257" border="0" cellspacing="0" cellpadding="0">

                                        <tr>
                                            <td width="13" style="background-color:#dfdfdf;">
                                                <img src= "http://link.ixs1.net/site/8554/images/gc_email-new_09.jpg" width="12" height="48" border="0" style="display:block;"/>
                                            </td>
                                            <td width="83" style="color:#E56D1F; font-family:Arial, Helvetica, sans-serif; font-size:24px; background-color:#dfdfdf;">
                                                <strong><%= number_to_currency(@first_deal.offer.options.first.pricing.price) %></strong></td>
                                            <td width="161">
                                                <a href="<%=  @first_deal.offer.url %>"><img src= "http://link.ixs1.net/site/8554/images/gc_email-new_11.jpg" border="0" width="161" height="48" alt="view deal" style="display:block;"/></a>
                                            </td>
                                        </tr>

                                    </table>
                                    <!--Button Area Table -->

                                    <img src= "http://link.ixs1.net/site/8554/images/gc_email-new_12.jpg" width="257" height="11" border="0" style="display:block;"/>

                                    <!--Value Area Table -->

                                    <table width="257" border="0" cellspacing="0" cellpadding="0">

                                        <tr>
                                            <td width="13">

                                            </td>
                                            <td width="244" style="color:#a8d1e9; font-family:Arial, Helvetica, sans-serif; font-size:24px;" valign="top">
                                                <del>Valued at <%=number_to_currency(@first_deal.offer.options.first.pricing.originalPrice)%></del>
                                            </td>
                                        </tr>

                                    </table>
                                    <!--Value Area Table -->


                                </td>
                            </tr>

                        </table>
                        <!--View Deal Table -->

                    </td>
                    <td width="39">
                        <img src= "http://link.ixs1.net/site/8554/images/gc_email-new_07.jpg" width="39" height="256" border="0"    style="display:block;"/>
                    </td>
                </tr>

            </table>
            <!--Main Deal Table -->
        </td>
    </tr>
    <tr>
        <td width="700">
            <img src= "http://link.ixs1.net/site/8554/images/gc_email-new_15.jpg" width="700" height="18" border="0" style="display:block;"/>
        </td>
    </tr>
    <tr>
        <td width="700">
            <table width="700" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td width="56">
                        <img src= "http://link.ixs1.net/site/8554/images/gc_email-new_16.jpg" width="56" height="200" border="0" style="display:block;"/>
                    </td>


                    <td width="604" valign="top">
                        <table width="604" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td width="604" style="font-size:13px; font-family:Arial, Helvetica, sans-serif;" valign="top">
                                    <span style="color:#e26522; font-size:24px; font-family:Arial, Helvetica, sans-serif;"><strong>Deal
                                            Highlights</strong></span><br />
                                </td>
                            </tr>
                            <tr>
                                <td width="604">
                                    <table width="604" border="0" cellspacing="0" cellpadding="0">

                                        <tr>
                                            <td width="604" style="color:#000; padding-top:5px; font-family:Arial, Helvetica, sans-serif; font-size:13px;">
                                                 <%= @first_deal.offer['copy'].html_safe %>
                                            </td>
                                        </tr>

                                    </table>
                                </td>
                            </tr>
                        </table>

                    </td>
                    <td width="40">
                        <img src= "http://link.ixs1.net/site/8554/images/gc_email-new_18.jpg" width="40" height="200" border="0" style="display:block;"/>
                    </td>
                </tr>

            </table>
        </td>
    </tr>
    <tr>
        <td width="700">
            <img src= "http://link.ixs1.net/site/8554/images/gc_email-new_19.jpg" alt="Other Great Offers!" width="700" height="89" border="0" style="display:block;"/>
        </td>
    </tr>
    <tr>
        <td width="700">
            <!--Last Chance Deals -->
            <table width="700" border="0" cellspacing="0" cellpadding="0">

                <tr>
                    <td width="60">
                        <img src= "http://link.ixs1.net/site/8554/images/gc_email-new_20.jpg" border="0" width="60" height="90" style="display:block;"/>
                    </td>
                    <td width="120">
                        <img src="<%=  @second_deal.offer.images.first.sizes[7].url %>" width="120" height="90" border="0" style="display:block;"/>
                    </td>
                    <td width="12">
                        <img src= "http://link.ixs1.net/site/8554/images/gc_email-new_22.jpg" width="12" height="90" border="0" style="display:block;"/>
                    </td>
                    <td width="169" style="background-color:#017dc3;">
                        <table width="169" border="0" cellspacing="0" cellpadding="0" style="background-color:#017dc3;">
                            <tr>
                                <td width="169" style="background-color:#017dc3;">
                                    <table width="169" border="0" cellspacing="0" cellpadding="0" style="background-color:#017dc3;">
                                        <tr>
                                            <td width="159" style="font-family:Arial, Helvetica, sans-serif; font-size:12px; background-color:#017dc3; color:#FFF;">
                                                 <%=  @second_deal.offer.headline %>
                                            </td>
                                            <td width="10"></td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr valign="bottom">
                                <td width="169" style="background-color:#017dc3;"  valign="bottom">
                                    <table width="169" border="0" cellspacing="0" cellpadding="0" style="background-color:#017dc3;">
                                        <tr>
                                            <td width="169" valign="bottom">
                                                <a href="<%=  @second_deal.offer.url %>"><img src=  "http://link.ixs1.net/site/8554/images/gc_email-new_28.jpg" width="169" height="38" border="0" alt="View Deal" style="display:block;"/></a>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>

                    <td width="120">
                        <img src="<%=  @third_deal.offer.images.first.sizes[7].url %>" width="120" height="90" border="0" style="display:block;"/>
                    </td>
                    <td width="13">
                        <img src= "http://link.ixs1.net/site/8554/images/gc_email-new_25.jpg" width="13" height="90" style="display:block;" border="0"/>
                    </td>
                    <td width="163" style="font-family:Arial, Helvetica, sans-serif; font-size:12px; background-color:#017dc3; color:#FFF; background-color:#017dc3;">
                      <%=  @third_deal.offer.headline %>
                        <a href="<%=  @third_deal.offer.url %>"><img src=  "http://link.ixs1.net/site/8554/images/gc_email-new_29.jpg" width="163" height="38" border="0" alt="View Deal" style="display:block;"/></a>
                    </td>
                    <td width="43">
                        <img src= "http://link.ixs1.net/site/8554/images/gc_email-new_27.jpg" width="43" height="90" style="display:block;" border="0"/>
                    </td>
                </tr>

            </table>
            <!--Last Chance Deals -->
        </td>
    </tr>
    <tr>
        <td width="700">
            <img src= "http://link.ixs1.net/site/8554/images/gc_email-new_30.jpg" width="700" height="49" border="0" style="display:block;"/>
        </td>
    </tr>
</table>

app/views/partials/_huggies_promo.html.erb
<div>
<h2>Save on Huggies Diapers and so much more!</h2>
Your baby is likely to need diapers for the foreseeable future... you might as well save on diapers as much as you can.
  <br />
  Members of deals for mommy
  have saved thousands on everything you need for your baby. From diapers to formula to clothes and more.
  <br />
  Join in on the savings, the community would love to have you.
</div>

app/views/partials/_kohls_promo.html.erb
<div>
  <h2>Save at Kohl's and so much more!</h2>
  Members of deals for mommy have saved thousands on everything you need for your family. <br />
  From diapers to formula to clothes and more. Join in on the savings, the community would love to have you.
</div>

app/views/partials/_marin_conversion.html.erb
<% if flash[:conversion_membership] %>
<script type="text/javascript">
    var _mTrack = _mTrack || [];
    _mTrack.push(['addTrans', {
        orderId : '<%=@member.id%>',
        total :   '0',
        currency : 'USD',
        items : [
         {
         orderId : '<%=@member.id%>',
         convType : 'membership',
         price :    '0'
        	}
        ]
    }]);
    
    _mTrack.push(['processOrders']);
    (function() {
        var mClientId = 'y7apyzuji0';
        var mProto = ('https:' == document.location.protocol ? 'https://' : 'http://');
        var mHost = 'tracker.marinsm.com';
        var mt = document.createElement('script'); mt.type = 'text/javascript'; mt.async = true; mt.src = mProto + mHost + '/tracker/async/' + mClientId + '.js';
        var fscr = document.getElementsByTagName('script')[0]; fscr.parentNode.insertBefore(mt, fscr);
    })();
</script>
<noscript>
    <img src="https://tracker.marinsm.com/tp?act=2&cid=4438pj420635&script=no" >
</noscript>

<!-- END: Copyright Marin Software -->



<% end %>

app/views/partials/_promoContainer.html.erb
<!-- Start promoContainer -->
  <div id="promoContainer">
    <h2><span style="width:145px">Moms Joined Today</span></h2>
    <h2><span>Members Inside</span></h2>
    <h2><span>Savings Inside</span></h2>

    <div id="stats">
      <span class="statsBorder" style="width:145px"><%= number_with_delimiter(@joined_today ||= 0) %></span>
      <span class="statsBorder"><%= number_with_delimiter(@member_count ||= 0) %></span>
      <span>$<%= savings_total %></span>
    </div>
    <!-- Start Promo -->
    <div id="promo">
	  <%if session[:pm_form]=~/piggy/%>
      	 <%= image_tag("dfm-ad-virtual-piggy_2.gif",:size=>'413x270') %>
	     <br /><br />
	<%= image_tag("dfm-ad-virtual-piggy-hiw-hdr_red.png")%>
	<div  style="margin:15px 5px 0 8px;">
		Virtual Piggy helps kids to learn money <br />management, by tracking:
		<br /><br />
		<div class="vp">
		<ol>
			<li >savings goals</li>
			<li>wishlists</li>
			<li>spending habits</li>
			<li>donations to charity</li>
		</ol>
		</div>
		<div class="clear"></div>
		<br />

		Kids have fun as they learn to manage their online budget and parents always have access to when and where money is being spent via controls you set up! Virtual Piggy is always 100% free to use. 
		<br /><br />

		<a href="" style="color:#f36e25;" onclick="window.open('/images/How-it-Works-2.jpg', 'mywindow', 'location=1,status=1,scrollbars=1,width=612,height=792');return false;"> Learn More</a> 
		or
		<a href="" style="color:#f36e25;" onclick="window.open('/virtual_piggy/video.html', 'mywindow', 'location=0,status=1,scrollbars=1,width=590,height=370');return false;"> Watch the Video</a> 
		
		</div>
		
      <%elsif params[:f]=~/moolala/%>
          <%= image_tag("dfm-diapers-ad_moolala.gif") %>
      <%elsif params[:f]=~/shopsocial/%>
      	  <%= image_tag("partner_pages/dfm_shopsocial_rightside.jpg") %>
	  <%else%>
          <% if @promo.try(:empty?) %>
            <script>utmx_section("section4")</script>
                <%= image_tag("dfm_bg-promo-green.jpg", :alt=>"Get access to the Best Free Samples, Local Savings, Weekly Coupons, and Daily Deals", :title=>"Best Free Samples, Local Savings, Weekly Coupons", :size=>'413x210') %>
            </noscript>
	      <% else %>
	        <%= image_tag("bg-promo-green-#{@promo}.png", :alt=>"Get access to the Best Free Samples, Local Savings, Weekly Coupons, and Daily Deals", :title=>"Best Free Samples, Local Savings, Weekly Coupons", :size=>'413x210') %>
	      <% end %>
      <% end %>


    </div>
    <!-- End Promo -->
  </div>
  <div class="clear"></div>
<!-- End promoContainer -->

app/views/partials/_target_promo.html.erb
<div>
  <h2>Save at Target and so much more!</h2>
  Members of deals for mommy have saved thousands on everything you need for your family.  <br />
  From diapers to formula to clothes and more.Join in on the savings, the community would love to have you.
</div>

app/views/partials/_thankyou_pixel.html.erb
<% if session[:thankyou_pixel]!= nil %>
    <!-- Google Code for Thank You Page Remarketing List 0517-->
    <script type="text/javascript">
/* <![CDATA[ */
    var google_conversion_id = 1001779244;
    var google_conversion_language = "en";
    var google_conversion_format = "3";
    var google_conversion_color = "ffffff";
    var google_conversion_label = "hQmdCIzR3wMQrODX3QM";
    var google_conversion_value = 0;
/* ]]> */
    </script>
    <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
    </script>
    <noscript>
    <div style="display:inline;">
    <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/1001779244/?label=hQmdCIzR3wMQrODX3QM&amp;guid=ON&amp;script=0"/>
    </div>
    </noscript>
    <% session.delete(:thankyou_pixel) %>
<%end%>

app/views/partials/_tracking.html.erb
<% if (true == @unconverted) || true %>
<!-- Google Website Optimizer Control Script -->
<script>
function utmx_section(){}function utmx(){}
(function(){var k='2080765054',d=document,l=d.location,c=d.cookie;function f(n){
if(c){var i=c.indexOf(n+'=');if(i>-1){var j=c.indexOf(';',i);return escape(c.substring(i+n.
length+1,j<0?c.length:j))}}}var x=f('__utmx'),xx=f('__utmxx'),h=l.hash;
d.write('<sc'+'ript src="'+
'http'+(l.protocol=='https:'?'s://ssl':'://www')+'.google-analytics.com'
+'/siteopt.js?v=1&utmxkey='+k+'&utmx='+(x?x:'')+'&utmxx='+(xx?xx:'')+'&utmxtime='
+new Date().valueOf()+(h?'&utmxhash='+escape(h.substr(1)):'')+
'" type="text/javascript" charset="utf-8"></sc'+'ript>')})();
</script>
<!-- End of Google Website Optimizer Control Script -->
<!-- Google Website Optimizer Tracking Script -->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['gwo._setAccount', 'UA-20971204-2']);
  _gaq.push(['gwo._trackPageview', '/2080765054/test']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<!-- End of Google Website Optimizer Tracking Script -->
<% end %>

<% if true == @converted %>
<!-- Google Website Optimizer Tracking Script -->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['gwo._setAccount', 'UA-20971204-2']);
  _gaq.push(['gwo._trackPageview', '/2080765054/goal']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<!-- End of Google Website Optimizer Tracking Script -->
<% end %>